"""Lays out arg config for macros, all args must be keywords. Defaults may be set here."""

def a(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", href="", hreflang="", inert="", inputmode="", lang="", media="", ping="", popover="", referrerpolicy="", rel="", spellcheck="", style="", tabindex="", target="", title="", translate="", type=""): pass
def abbr(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def address(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def area(classes="", id="", accesskey="", alt="", contenteditable="", coords="", dir="", download="", draggable="", enterkeyhint="", hidden="", hreflang="", inert="", inputmode="", lang="", media="", popover="", referrerpolicy="", rel="", shape="", spellcheck="", style="", tabindex="", target="", title="", translate="", type=""): pass
def article(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def aside(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def audio(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", preload="", spellcheck="", src="", style="", tabindex="", title="", translate=""): pass
def b(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def base(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", href="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", target="", title="", translate=""): pass
def bdi(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def bdo(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def blockquote(content="", classes="", id="", accesskey="", cite="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def body(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def br(classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def button(content="", classes="", id="", accesskey="", autofocus="", contenteditable="", dir="", disabled="", draggable="", enterkeyhint="", form="", formaction="", formenctype="", formmethod="", formnovalidate="", formtarget="", hidden="", inert="", inputmode="", lang="", name="", popover="", popovertarget="", popovertargetaction="", spellcheck="", style="", tabindex="", title="", translate="", type="", value=""): pass
def canvas(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", height="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate="", width=""): pass
def caption(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def cite(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def code(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def col(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", span="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def colgroup(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", span="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def data(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate="", value=""): pass
def datalist(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def dd(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def del_(content="", classes="", id="", accesskey="", cite="", contenteditable="", datetime="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def details(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", open="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def dfn(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def dialog(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", open="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def div(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def dl(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def dt(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def em(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def embed(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", height="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", src="", style="", tabindex="", title="", translate="", type="", width=""): pass
def fieldset(content="", classes="", id="", accesskey="", contenteditable="", dir="", disabled="", draggable="", enterkeyhint="", form="", hidden="", inert="", inputmode="", lang="", name="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def figcaption(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def figure(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def footer(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def form(content="", classes="", id="", accept_charset="", accesskey="", action="", autocomplete="", contenteditable="", dir="", draggable="", enctype="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", method="", name="", novalidate="", popover="", rel="", spellcheck="", style="", tabindex="", target="", title="", translate=""): pass
def h1(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def h2(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def h3(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def h4(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def h5(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def h6(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def head(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def header(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def hgroup(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def hr(classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def html(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate="", xmlns=""): pass
def i(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def iframe(content="", classes="", id="", accesskey="", allow="", allowfullscreen="", allowpaymentrequest="", contenteditable="", dir="", draggable="", enterkeyhint="", height="", hidden="", inert="", inputmode="", lang="", loading="", name="", popover="", referrerpolicy="", sandbox="", spellcheck="", src="", srcdoc="", style="", tabindex="", title="", translate="", width=""): pass
def img(content="", classes="", id="", accesskey="", alt="", contenteditable="", crossorigin="", dir="", draggable="", enterkeyhint="", height="", hidden="", inert="", inputmode="", ismap="", lang="", loading="", longdesc="", popover="", referrerpolicy="", sizes="", spellcheck="", src="", srcset="", style="", tabindex="", title="", translate="", usemap="", width=""): pass
def input(classes="", id="", accept="", accesskey="", alt="", autocomplete="", autofocus="", checked="", contenteditable="", dir="", dirname="", disabled="", draggable="", enterkeyhint="", form="", formaction="", formenctype="", formmethod="", formnovalidate="", formtarget="", height="", hidden="", inert="", inputmode="", lang="", list="", max="", maxlength="", min="", minlength="", multiple="", name="", pattern="", placeholder="", popover="", popovertarget="", popovertargetaction="", readonly="", required="", size="", spellcheck="", src="", step="", style="", tabindex="", title="", translate="", type="", value="", width=""): pass
def ins(content="", classes="", id="", accesskey="", cite="", contenteditable="", datetime="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def kbd(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def label(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", for_="", form="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def legend(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def li(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate="", value=""): pass
def link(classes="", id="", accesskey="", contenteditable="", crossorigin="", dir="", draggable="", enterkeyhint="", hidden="", href="", hreflang="", inert="", inputmode="", lang="", media="", popover="", referrerpolicy="", rel="", sizes="", spellcheck="", style="", tabindex="", title="", translate="", type=""): pass
def main(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def map_(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", name="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def mark(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def menu(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def meta(content="", classes="", id="", accesskey="", charset="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", http_equiv="", inert="", inputmode="", lang="", name="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def meter(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", form="", hidden="", high="", inert="", inputmode="", lang="", low="", max="", min="", optimum="", popover="", spellcheck="", style="", tabindex="", title="", translate="", value=""): pass
def nav(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def noscript(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def object_(content="", classes="", id="", accesskey="", contenteditable="", data="", dir="", draggable="", enterkeyhint="", form="", height="", hidden="", inert="", inputmode="", lang="", name="", popover="", spellcheck="", style="", tabindex="", title="", translate="", type="", typemustmatch="", usemap="", width=""): pass
def ol(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", reversed="", spellcheck="", start="", style="", tabindex="", title="", translate="", type=""): pass
def optgroup(content="", classes="", id="", accesskey="", contenteditable="", dir="", disabled="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", label="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def option(content="", classes="", id="", accesskey="", contenteditable="", dir="", disabled="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", label="", lang="", popover="", selected="", spellcheck="", style="", tabindex="", title="", translate="", value=""): pass
def output(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", for_="", form="", hidden="", inert="", inputmode="", lang="", name="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def p(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def param(classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", name="", popover="", spellcheck="", style="", tabindex="", title="", translate="", value=""): pass
def picture(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def pre(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def progress(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", max="", popover="", spellcheck="", style="", tabindex="", title="", translate="", value=""): pass
def q(content="", classes="", id="", accesskey="", cite="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def rp(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def rt(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def ruby(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def s(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def samp(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def script(content="", classes="", id="", accesskey="", async_="", contenteditable="", crossorigin="", defer="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", integrity="", lang="", nomodule="", popover="", referrerpolicy="", spellcheck="", src="", style="", tabindex="", title="", translate="", type=""): pass
def search(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def section(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def select(content="", classes="", id="", accesskey="", autofocus="", contenteditable="", dir="", disabled="", draggable="", enterkeyhint="", form="", hidden="", inert="", inputmode="", lang="", multiple="", name="", popover="", required="", size="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def small(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def source(classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", media="", popover="", sizes="", spellcheck="", src="", srcset="", style="", tabindex="", title="", translate="", type=""): pass
def span(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def strong(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def style(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", media="", popover="", spellcheck="", style="", tabindex="", title="", translate="", type=""): pass
def sub(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def summary(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def sup(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def svg(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def table(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def tbody(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def td(content="", classes="", id="", accesskey="", colspan="", contenteditable="", dir="", draggable="", enterkeyhint="", headers="", hidden="", inert="", inputmode="", lang="", popover="", rowspan="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def template(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def textarea(content="", classes="", id="", accesskey="", autofocus="", cols="", contenteditable="", dir="", dirname="", disabled="", draggable="", enterkeyhint="", form="", hidden="", inert="", inputmode="", lang="", maxlength="", name="", placeholder="", popover="", readonly="", required="", rows="", spellcheck="", style="", tabindex="", title="", translate="", wrap=""): pass
def tfoot(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def th(content="", classes="", id="", abbr="", accesskey="", colspan="", contenteditable="", dir="", draggable="", enterkeyhint="", headers="", hidden="", inert="", inputmode="", lang="", popover="", rowspan="", scope="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def thead(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def time(content="", classes="", id="", accesskey="", contenteditable="", datetime="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def title(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def tr(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def track(classes="", id="", accesskey="", contenteditable="", default="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", kind="", label="", lang="", popover="", spellcheck="", src="", srclang="", style="", tabindex="", title="", translate=""): pass
def u(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def ul(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def var(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def video(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def wbr(content="", classes="", id="", accesskey="", contenteditable="", dir="", draggable="", enterkeyhint="", hidden="", inert="", inputmode="", lang="", popover="", spellcheck="", style="", tabindex="", title="", translate=""): pass
def comment(content=""): pass
def doctype(): pass
